export interface TipoContratacionCatalogo {
  id: string;
  descripcion: string;
}

/** Tipos de contratación agrupados por ID de administración */
export const TIPOS_CONTRATACION_BY_ADMIN: Record<string, TipoContratacionCatalogo[]> = {
  '1': [
    { id: '1',     descripcion: 'ALTA NUEVA DOMESTICO APOYO SOCIAL' },
    { id: '21',    descripcion: 'BAJA SUMINISTRO DOMESTICO MEDIO' },
    { id: '41',    descripcion: 'ALTA NUEVA DOMESTICO ECONÓMICO' },
    { id: '42',    descripcion: 'ALTA NUEVA DOMESTICO MEDIO' },
    { id: '43',    descripcion: 'ALTA NUEVA DOMESTICO ALTO' },
    { id: '44',    descripcion: 'ALTA NUEVA COMERCIAL' },
    { id: '45',    descripcion: 'ALTA NUEVA INDUSTRIAL' },
    { id: '47',    descripcion: 'ALTA NUEVA PUBLICO OFICIAL' },
    { id: '48',    descripcion: 'ALTA NUEVA PUBLICO CONCESIONADO' },
    { id: '49',    descripcion: 'ALTA NUEVA INST. DE BENEFICIENCIA' },
    { id: '50',    descripcion: 'ALTA NUEVA HIDRANTE' },
    { id: '51',    descripcion: 'BAJA SUMINISTRO PUBLICO OFICIAL' },
    { id: '52',    descripcion: 'BAJA SUMINISTRO PUBLICO CONCESIONADO' },
    { id: '53',    descripcion: 'BAJA SUMINISTRO INDUSTRIAL' },
    { id: '54',    descripcion: 'BAJA SUMINISTRO INST. DE BENEFICIENCIA' },
    { id: '55',    descripcion: 'BAJA SUMINISTRO COMERCIAL' },
    { id: '421',   descripcion: 'ALTA P. BAJA PUBLICO OFICIAL' },
    { id: '422',   descripcion: 'ALTA P. BAJA PUBLICO CONCESIONADO' },
    { id: '423',   descripcion: 'ALTA P. BAJA INST. DE BENEFICIENCIA' },
    { id: '424',   descripcion: 'ALTA P. BAJA INDUSTRIAL' },
    { id: '425',   descripcion: 'ALTA P. BAJA HIDRANTE' },
    { id: '426',   descripcion: 'ALTA P. BAJA DOMESTICO MEDIO CONDOMINAL' },
    { id: '427',   descripcion: 'ALTA P. BAJA DOMESTICO ECONOMICO' },
    { id: '429',   descripcion: 'ALTA P. BAJA DOMESTICO APOYO SOCIAL' },
    { id: '430',   descripcion: 'ALTA P. BAJA DOMESTICO ALTO' },
    { id: '431',   descripcion: 'ALTA PA COMERCIAL' },
    { id: '611',   descripcion: 'GESTION INTERNA' },
    { id: '761',   descripcion: 'BAJA SUMINISTRO HIDRANTE' },
    { id: '862',   descripcion: 'BAJA SUMINISTRO DOMESTICO ALTO' },
    { id: '863',   descripcion: 'BAJA SUMINISTRO DOMESTICO APOYO SOCIAL' },
    { id: '864',   descripcion: 'BAJA SUMINISTRO DOMESTICO ECONÓMICO' },
    { id: '941',   descripcion: 'CONTRATOS ESPECIALES' },
    { id: '943',   descripcion: 'ALTA NUEVA DOMESTICO MEDIO CONDOMINAL' },
    { id: '944',   descripcion: 'ALTA NUEVA DOMÉSTICO ECONÓMICO CONDOMINAL' },
    { id: '945',   descripcion: 'ALTA NUEVA DOMESTICO ALTO CONDOMINAL' },
    { id: '946',   descripcion: 'ALTA NUEVA COMERCIAL CONDOMINAL' },
    { id: '947',   descripcion: 'ALTA P. BAJA DOMESTICO MEDIO' },
    { id: '948',   descripcion: 'ALTA P. BAJA DOMÉSTICO ECONÓMICO CONDOMINAL' },
    { id: '949',   descripcion: 'ALTA P. BAJA DOMESTICO ALTO CONDOMINAL' },
    { id: '950',   descripcion: 'ALTA P. BAJA COMERCIAL CONDOMINAL' },
    { id: '951',   descripcion: 'ALTA NUEVA DOMESTICO APOYO SOCIAL CONDOMINAL' },
    { id: '952',   descripcion: 'ALTA P. BAJA DOMESTICO APOYO SOCIAL CONDOMINAL' },
    { id: '1065',  descripcion: 'ALTA NUEVA DOMESTICO MEDIO INDIVIDUAL PROVISIONAL' },
    { id: '1066',  descripcion: 'ALTA NUEVA DOMESTICO MEDIO CONDOMINAL PROVISIONAL' },
    { id: '1067',  descripcion: 'ALTA NUEVA DOMESTICO ECONÓMICO INDIVIDUAL PROVISIONAL' },
    { id: '1068',  descripcion: 'ALTA NUEVA DOMESTICO ECONÓMICO CONDOMINAL PROVISIONAL' },
    { id: '1098',  descripcion: 'ALTA NUEVA DOMESTICO APOYO SOCIAL CONDOMINAL PROVISIONAL' },
    { id: '1099',  descripcion: 'ALTA NUEVA DOMESTICO APOYO SOCIAL INDIVIDUAL PROVISIONAL' },
    { id: '1100',  descripcion: 'ALTA NUEVA DOMÉSTICO ALTO CONDOMINAL PROVISIONAL' },
    { id: '1101',  descripcion: 'ALTA NUEVA DOMÉSTICO ALTO INDIVIDUAL PROVISIONAL' },
    { id: '1102',  descripcion: 'ALTA NUEVA COMERCIAL CONDOMINAL PROVISIONAL' },
    { id: '1103',  descripcion: 'ALTA NUEVA COMERCIAL INDIVIDUAL PROVISIONAL' },
    { id: '1104',  descripcion: 'ALTA NUEVA HIDRANTE CONDOMINAL PROVISIONAL' },
    { id: '1105',  descripcion: 'ALTA NUEVA HIDRANTE INDIVIDUAL PROVISIONAL' },
    { id: '1106',  descripcion: 'ALTA NUEVA INDUSTRIAL CONDOMINAL PROVISIONAL' },
    { id: '1107',  descripcion: 'ALTA NUEVA INDUSTRIAL INDIVIDUAL PROVISIONAL' },
    { id: '1108',  descripcion: 'ALTA NUEVA PUBLICO OFICIAL CONDOMINAL PROVISIONAL' },
    { id: '1109',  descripcion: 'ALTA NUEVA PUBLICO OFICIAL INDIVIDUAL PROVISIONAL' },
    { id: '1110',  descripcion: 'ALTA NUEVA PUBLICO CONCESIONADO CONDOMINAL PROVISIONAL' },
    { id: '1111',  descripcion: 'ALTA NUEVA PUBLICO CONCESIONADO INDIVIDUAL PROVISIONAL' },
    { id: '1112',  descripcion: 'ALTA NUEVA INST. DE BENEFICIENCIA CONDOMINAL PROVISIONAL' },
    { id: '1113',  descripcion: 'ALTA NUEVA INST. DE BENEFICIENCIA INDIVIDUAL PROVISIONAL' },
    { id: '1131',  descripcion: 'ALTA P. BAJA COMERCIAL INDIVIDUAL PROVISIONAL' },
    { id: '1132',  descripcion: 'ALTA P. BAJA COMERCIAL CONDOMINAL PROVISIONAL' },
    { id: '1133',  descripcion: 'ALTA P. BAJA DOMÉSTICO ALTO INDIVIDUAL PROVISIONAL' },
    { id: '1134',  descripcion: 'ALTA P. BAJA DOMÉSTICO ALTO CONDOMINAL PROVISIONAL' },
    { id: '1135',  descripcion: 'ALTA P. BAJA DOMESTICO APOYO SOCIAL CONDOMINAL PROVISIONAL' },
    { id: '1136',  descripcion: 'ALTA P. BAJA DOMESTICO APOYO SOCIAL INDIVIDUAL PROVISIONAL' },
    { id: '1137',  descripcion: 'ALTA P. BAJA DOMÉSTICO ECONÓMICO CONDOMINAL PROVISIONAL' },
    { id: '1138',  descripcion: 'ALTA P. BAJA DOMÉSTICO ECONÓMICO INDIVIDUAL PROVISIONAL' },
    { id: '1139',  descripcion: 'ALTA P. BAJA DOMESTICO MEDIO CONDOMINAL PROVISIONAL' },
    { id: '1140',  descripcion: 'ALTA P. BAJA DOMESTICO MEDIO INDIVIDUAL PROVISIONAL' },
    { id: '1141',  descripcion: 'ALTA P. BAJA HIDRANTE CONDOMINAL PROVISIONAL' },
    { id: '1142',  descripcion: 'ALTA P. BAJA HIDRANTE INDIVIDUAL PROVISIONAL' },
    { id: '1143',  descripcion: 'ALTA P. BAJA INDUSTRIAL CONDOMINAL PROVISIONAL' },
    { id: '1144',  descripcion: 'ALTA P. BAJA INDUSTRIAL INDIVIDUAL PROVISIONAL' },
    { id: '1145',  descripcion: 'ALTA P. BAJA INST. DE BENEFICIENCIA CONDOMINAL PROVISIONAL' },
    { id: '1146',  descripcion: 'ALTA P. BAJA INST. DE BENEFICIENCIA INDIVIDUAL PROVISIONAL' },
    { id: '1147',  descripcion: 'ALTA P. BAJA PUBLICO CONCESIONADO CONDOMINAL PROVISIONAL' },
    { id: '1148',  descripcion: 'ALTA P. BAJA PUBLICO CONCESIONADO INDIVIDUAL PROVISIONAL' },
    { id: '1149',  descripcion: 'ALTA P. BAJA PUBLICO OFICIAL CONDOMINAL PROVISIONAL' },
    { id: '1150',  descripcion: 'ALTA P. BAJA PUBLICO OFICIAL INDIVIDUAL PROVISIONAL' },
    { id: '1151',  descripcion: 'BAJA SUMINISTRO COMERCIAL INDIVIDUAL PROVISIONAL' },
    { id: '1152',  descripcion: 'BAJA SUMINISTRO COMERCIAL CONDOMINAL PROVISIONAL' },
    { id: '1153',  descripcion: 'BAJA SUMINISTRO DOMESTICO ALTO CONDOMINAL PROVISIONAL' },
    { id: '1154',  descripcion: 'BAJA SUMINISTRO DOMESTICO ALTO INDIVIDUAL PROVISIONAL' },
    { id: '1155',  descripcion: 'BAJA SUMINISTRO DOMESTICO APOYO SOCIAL INDIVIDUAL PROVISIONAL' },
    { id: '1156',  descripcion: 'BAJA SUMINISTRO DOMESTICO APOYO SOCIAL CONDOMINAL PROVISIONAL' },
    { id: '1157',  descripcion: 'BAJA SUMINISTRO DOMÉSTICO ECONÓMICO CONDOMINAL PROVISIONAL' },
    { id: '1158',  descripcion: 'BAJA SUMINISTRO DOMÉSTICO ECONÓMICO INDIVIDUAL PROVISIONAL' },
    { id: '1159',  descripcion: 'BAJA SUMINISTRO DOMÉSTICO MEDIO CONDOMINAL PROVISIONAL' },
    { id: '1160',  descripcion: 'BAJA SUMINISTRO DOMÉSTICO MEDIO INDIVIDUAL PROVISIONAL' },
    { id: '1161',  descripcion: 'BAJA SUMINISTRO HIDRANTE CONDOMINAL PROVISIONAL' },
    { id: '1162',  descripcion: 'BAJA SUMINISTRO HIDRANTE INDIVIDUAL PROVISIONAL' },
    { id: '1163',  descripcion: 'BAJA SUMINISTRO INDUSTRIAL CONDOMINAL PROVISIONAL' },
    { id: '1164',  descripcion: 'BAJA SUMINISTRO INDUSTRIAL INDIVIDUAL PROVISIONAL' },
    { id: '1165',  descripcion: 'BAJA SUMINISTRO INST. DE BENEFICIENCIA CONDOMINAL PROVISIONAL' },
    { id: '1166',  descripcion: 'BAJA SUMINISTRO INST. DE BENEFICIENCIA INDIVIDUAL PROVISIONAL' },
    { id: '1167',  descripcion: 'BAJA SUMINISTRO PUBLICO CONCESIONADO CONDOMINAL PROVISIONAL' },
    { id: '1168',  descripcion: 'BAJA SUMINISTRO PUBLICO CONCESIONADO INDIVIDUAL PROVISIONAL' },
    { id: '1169',  descripcion: 'BAJA SUMINISTRO PUBLICO OFICIAL CONDOMINAL PROVISIONAL' },
    { id: '1170',  descripcion: 'BAJA SUMINISTRO PUBLICO OFICIAL INDIVIDUAL PROVISIONAL' },
    { id: '80495', descripcion: 'SIN SUMINISTRO DOMESTICO ALTO INDIVIDUAL PROVISIONAL' },
    { id: '80858', descripcion: 'ALTA NUEVA ALCANTARILLADO Y/O SANEAMIENTO INDUSTRIAL' },
    { id: '80891', descripcion: 'ALTA NUEVA AGUA TRATADA' },
  ],

  '2': [
    { id: '2001', descripcion: 'ALTA NUEVA PUBLICO OFICIAL' },
    { id: '2002', descripcion: 'ALTA NUEVA PUBLICO CONCESIONADO' },
    { id: '2003', descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL' },
    { id: '2004', descripcion: 'ALTA NUEVA COMERCIAL' },
    { id: '2005', descripcion: 'ALTA NUEVA INDUSTRIAL' },
    { id: '2006', descripcion: 'BAJA SUMINISTRO DOMESTICO ZONA RURAL' },
    { id: '2007', descripcion: 'ALTA NUEVA INST. DE BENEFICIENCIA' },
    { id: '2008', descripcion: 'BAJA SUMINISTRO PUBLICO OFICIAL' },
    { id: '2009', descripcion: 'BAJA SUMINISTRO PUBLICO CONCESIONADO' },
    { id: '2010', descripcion: 'BAJA SUMINISTRO INDUSTRIAL' },
    { id: '2011', descripcion: 'BAJA SUMINISTRO INST. DE BENEFICIENCIA' },
    { id: '2012', descripcion: 'BAJA SUMINISTRO COMERCIAL' },
    { id: '2013', descripcion: 'ALTA NUEVA DOMESTICO ALTO' },
    { id: '2014', descripcion: 'ALTA P. BAJA GANADERO' },
    { id: '2015', descripcion: 'ALTA P. BAJA PUBLICO OFICIAL' },
    { id: '2016', descripcion: 'ALTA P. BAJA PUBLICO CONCESIONADO' },
    { id: '2017', descripcion: 'ALTA P. BAJA INST. DE BENEFICIENCIA' },
    { id: '2018', descripcion: 'ALTA P. BAJA INDUSTRIAL' },
    { id: '2019', descripcion: 'BAJA SUMINISTRO GANADERO' },
    { id: '2020', descripcion: 'ALTA P. BAJA DOMESTICO ZONA RURAL' },
    { id: '2021', descripcion: 'ALTA P. BAJA COMERCIAL' },
    { id: '2022', descripcion: 'BAJA SUMINISTRO HIDRANTE' },
    { id: '2023', descripcion: 'ALTA P. BAJA DOMESTICO ALTO' },
    { id: '2024', descripcion: 'GESTION INTERNA' },
    { id: '2025', descripcion: 'ALTA NUEVA HIDRANTE' },
    { id: '2026', descripcion: 'ALTA NUEVA DOMESTICO CABECERA MEDIA' },
    { id: '2027', descripcion: 'ALTA P. BAJA HIDRANTE' },
    { id: '2028', descripcion: 'ALTA P. BAJA DOMESTICO CABECERA MEDIA' },
    { id: '2029', descripcion: 'ALTA NUEVA GANADERO' },
    { id: '2030', descripcion: 'BAJA SUMINISTRO DOMESTICO CABECERA MEDIA' },
    { id: '2031', descripcion: 'BAJA SUMINISTRO DOMESTICO CABECERA ECONÓMICA' },
    { id: '2032', descripcion: 'ALTA P. BAJA DOMESTICO ECONOMICO' },
    { id: '2033', descripcion: 'ALTA NUEVA DOMESTICO CABECERA MEDIA CONDOMINAL' },
    { id: '2034', descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL CONDOMINAL' },
    { id: '2035', descripcion: 'ALTA NUEVA COMERCIAL CONDOMINAL' },
    { id: '2036', descripcion: 'BAJA SUMINISTRO DOMESTICO ECONOMICO' },
    { id: '2037', descripcion: 'ALTA P. BAJA DOMESTICO CABECERA MEDIA CONDOMINAL' },
    { id: '2038', descripcion: 'ALTA P. BAJA DOMESTICO ZONA RURAL CONDOMINAL' },
    { id: '2039', descripcion: 'ALTA P. BAJA COMERCIAL CONDOMINAL' },
    { id: '2040', descripcion: 'ALTA NUEVA DOMESTICO ECONOMICO' },
    { id: '2041', descripcion: 'CONTRATOS ESPECIALES' },
    { id: '2042', descripcion: 'ALTA NUEVA DOMESTICO MEDIO' },
    { id: '2043', descripcion: 'BAJA SUMINISTRO DOMESTICO MEDIO' },
    { id: '2044', descripcion: 'BAJA SUMINISTRO DOMESTICO ALTO' },
    { id: '2045', descripcion: 'ALTA P. BAJA DOMESTICO MEDIO' },
  ],

  '3': [
    { id: '121',   descripcion: 'ALTA NUEVA PUBLICO OFICIAL' },
    { id: '132',   descripcion: 'ALTA NUEVA PUBLICO CONCESIONADO' },
    { id: '143',   descripcion: 'ALTA NUEVA INST. DE BENEFICIENCIA' },
    { id: '165',   descripcion: 'BAJA SUMINISTRO PUBLICO OFICIAL' },
    { id: '176',   descripcion: 'BAJA SUMINISTRO PUBLICO CONCESIONADO' },
    { id: '187',   descripcion: 'BAJA SUMINISTRO INDUSTRIAL' },
    { id: '198',   descripcion: 'BAJA SUMINISTRO INST. DE BENEFICIENCIA' },
    { id: '209',   descripcion: 'BAJA SUMINISTRO COMERCIAL' },
    { id: '363',   descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL' },
    { id: '374',   descripcion: 'ALTA NUEVA COMERCIAL' },
    { id: '385',   descripcion: 'ALTA NUEVA INDUSTRIAL' },
    { id: '396',   descripcion: 'BAJA SUMINISTRO DOMESTICO ZONA RURAL' },
    { id: '433',   descripcion: 'ALTA P. BAJA PUBLICO OFICIAL' },
    { id: '445',   descripcion: 'ALTA P. BAJA PUBLICO CONCESIONADO' },
    { id: '457',   descripcion: 'ALTA P. BAJA INST. DE BENEFICIENCIA' },
    { id: '469',   descripcion: 'ALTA P. BAJA INDUSTRIAL' },
    { id: '529',   descripcion: 'ALTA P. BAJA DOMESTICO ZONA RURAL' },
    { id: '553',   descripcion: 'ALTA P. BAJA COMERCIAL' },
    { id: '604',   descripcion: 'GESTION INTERNA' },
    { id: '636',   descripcion: 'ALTA P. BAJA DOMESTICO CABECERA MEDIA' },
    { id: '672',   descripcion: 'ALTA NUEVA GANADERO' },
    { id: '724',   descripcion: 'ALTA P. BAJA GANADERO' },
    { id: '736',   descripcion: 'BAJA SUMINISTRO GANADERO' },
    { id: '763',   descripcion: 'ALTA NUEVA DOMESTICO CABECERA MEDIA' },
    { id: '784',   descripcion: 'ALTA NUEVA HIDRANTE' },
    { id: '796',   descripcion: 'ALTA P. BAJA HIDRANTE' },
    { id: '848',   descripcion: 'BAJA SUMINISTRO DOMESTICO CABECERA ECONÓMICA' },
    { id: '849',   descripcion: 'BAJA SUMINISTRO DOMESTICO CABECERA MEDIA' },
    { id: '983',   descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL CONDOMINAL' },
    { id: '984',   descripcion: 'ALTA NUEVA DOMESTICO CABECERA MEDIA CONDOMINAL' },
    { id: '985',   descripcion: 'ALTA NUEVA COMERCIAL CONDOMINAL' },
    { id: '986',   descripcion: 'ALTA P. BAJA DOMESTICO ZONA RURAL CONDOMINAL' },
    { id: '987',   descripcion: 'ALTA P. BAJA DOMESTICO CABECERA MEDIA CONDOMINAL' },
    { id: '988',   descripcion: 'ALTA P. BAJA COMERCIAL CONDOMINAL' },
    { id: '1007',  descripcion: 'CONTRATO ESPECIAL' },
    { id: '1047',  descripcion: 'ALTA NUEVA DOMESTICO ECONOMICO' },
    { id: '1048',  descripcion: 'ALTA P. BAJA DOMESTICO ECONOMICO' },
    { id: '1049',  descripcion: 'BAJA SUMINISTRO DOMESTICO ECONOMICO' },
    { id: '1263',  descripcion: 'ALTA NUEVA DOMESTICO MEDIO' },
    { id: '1264',  descripcion: 'BAJA SUMINISTRO DOMESTICO MEDIO' },
    { id: '1265',  descripcion: 'ALTA P. BAJA DOMESTICO MEDIO' },
    { id: '80429', descripcion: 'ALTA NUEVA DOMESTICO ALTO' },
    { id: '80430', descripcion: 'BAJA SUMINISTRO DOMESTICO ALTO' },
    { id: '80431', descripcion: 'ALTA P. BAJA DOMESTICO ALTO' },
  ],

  '4': [
    { id: '122',   descripcion: 'ALTA NUEVA PUBLICO OFICIAL' },
    { id: '133',   descripcion: 'ALTA NUEVA PUBLICO CONCESIONADO' },
    { id: '144',   descripcion: 'ALTA NUEVA INST. DE BENEFICIENCIA' },
    { id: '166',   descripcion: 'BAJA SUMINISTRO PUBLICO OFICIAL' },
    { id: '177',   descripcion: 'BAJA SUMINISTRO PUBLICO CONCESIONADO' },
    { id: '188',   descripcion: 'BAJA SUMINISTRO INDUSTRIAL' },
    { id: '199',   descripcion: 'BAJA SUMINISTRO INST. DE BENEFICIENCIA' },
    { id: '210',   descripcion: 'BAJA SUMINISTRO COMERCIAL' },
    { id: '331',   descripcion: 'ALTA NUEVA DOMESTICO CABECERA ECONÓMICA' },
    { id: '364',   descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL' },
    { id: '375',   descripcion: 'ALTA NUEVA COMERCIAL' },
    { id: '386',   descripcion: 'ALTA NUEVA INDUSTRIAL' },
    { id: '397',   descripcion: 'BAJA SUMINISTRO DOMESTICO ZONA RURAL' },
    { id: '434',   descripcion: 'ALTA P. BAJA PUBLICO OFICIAL' },
    { id: '446',   descripcion: 'ALTA P. BAJA PUBLICO CONCESIONADO' },
    { id: '458',   descripcion: 'ALTA P. BAJA INST. DE BENEFICIENCIA' },
    { id: '470',   descripcion: 'ALTA P. BAJA INDUSTRIAL' },
    { id: '506',   descripcion: 'ALTA P. BAJA DOMESTICO CABECERA ECONÓMICA' },
    { id: '530',   descripcion: 'ALTA P. BAJA DOMESTICO ZONA RURAL' },
    { id: '554',   descripcion: 'ALTA P. BAJA COMERCIAL' },
    { id: '609',   descripcion: 'GESTION INTERNA' },
    { id: '677',   descripcion: 'ALTA NUEVA GANADERO' },
    { id: '729',   descripcion: 'ALTA P. BAJA GANADERO' },
    { id: '741',   descripcion: 'BAJA SUMINISTRO GANADERO' },
    { id: '789',   descripcion: 'ALTA NUEVA HIDRANTE' },
    { id: '801',   descripcion: 'ALTA P. BAJA HIDRANTE' },
    { id: '858',   descripcion: 'BAJA SUMINISTRO DOMESTICO CABECERA ECONÓMICA' },
    { id: '859',   descripcion: 'BAJA SUMINISTRO DOMESTICO CABECERA MEDIA' },
    { id: '967',   descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL CONDOMINAL' },
    { id: '968',   descripcion: 'ALTA NUEVA DOMESTICO CABECERA ECONÓMICA CONDOMINAL' },
    { id: '969',   descripcion: 'ALTA NUEVA COMERCIAL CONDOMINAL' },
    { id: '970',   descripcion: 'ALTA P. BAJA DOMESTICO ZONA RURAL CONDOMINAL' },
    { id: '971',   descripcion: 'ALTA P. BAJA DOMESTICO CABECERA ECONÓMICA CONDOMINAL' },
    { id: '972',   descripcion: 'ALTA P. BAJA COMERCIAL CONDOMINAL' },
    { id: '1026',  descripcion: 'CONTRATOS ESPECIALES' },
    { id: '1029',  descripcion: 'ALTA NUEVA DOMESTICO APOYO SOCIAL' },
    { id: '1030',  descripcion: 'BAJA SUMINISTRO DOMESTICO APOYO SOCIAL' },
    { id: '1031',  descripcion: 'ALTA P. BAJA DOMESTICO APOYO SOCIAL' },
    { id: '80048', descripcion: 'ALTA NUEVA DOMESTICO ECONÓMICO' },
    { id: '80049', descripcion: 'ALTA P. BAJA DOMESTICO ECONÓMICO' },
    { id: '80050', descripcion: 'BAJA SUMINISTRO DOMESTICO ECONÓMICO' },
    { id: '80367', descripcion: 'ALTA NUEVA DOMESTICO MEDIO' },
    { id: '80368', descripcion: 'ALTA NUEVA DOMESTICO ALTO' },
    { id: '80369', descripcion: 'BAJA SUMINISTRO DOMESTICO MEDIO' },
    { id: '80370', descripcion: 'BAJA SUMINISTRO DOMESTICO ALTO' },
    { id: '80371', descripcion: 'ALTA P. BAJA DOMESTICO MEDIO' },
    { id: '80372', descripcion: 'ALTA P. BAJA DOMESTICO ALTO' },
  ],

  '5': [
    { id: '123',   descripcion: 'ALTA NUEVA PUBLICO OFICIAL' },
    { id: '134',   descripcion: 'ALTA NUEVA PUBLICO CONCESIONADO' },
    { id: '145',   descripcion: 'ALTA NUEVA INST. DE BENEFICIENCIA' },
    { id: '167',   descripcion: 'BAJA SUMINISTRO PUBLICO OFICIAL' },
    { id: '178',   descripcion: 'BAJA SUMINISTRO PUBLICO CONCESIONADO' },
    { id: '189',   descripcion: 'BAJA SUMINISTRO INDUSTRIAL' },
    { id: '200',   descripcion: 'BAJA SUMINISTRO INST. DE BENEFICIENCIA' },
    { id: '211',   descripcion: 'BAJA SUMINISTRO COMERCIAL' },
    { id: '365',   descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL' },
    { id: '376',   descripcion: 'ALTA NUEVA COMERCIAL' },
    { id: '387',   descripcion: 'ALTA NUEVA INDUSTRIAL' },
    { id: '398',   descripcion: 'BAJA SUMINISTRO DOMESTICO ZONA RURAL' },
    { id: '435',   descripcion: 'ALTA P. BAJA PUBLICO OFICIAL' },
    { id: '447',   descripcion: 'ALTA P. BAJA PUBLICO CONCESIONADO' },
    { id: '459',   descripcion: 'ALTA P. BAJA INST. DE BENEFICIENCIA' },
    { id: '471',   descripcion: 'ALTA P. BAJA INDUSTRIAL' },
    { id: '507',   descripcion: 'ALTA P. BAJA DOMESTICO ZONA RURAL' },
    { id: '555',   descripcion: 'ALTA P. BAJA COMERCIAL' },
    { id: '613',   descripcion: 'GESTION INTERNA' },
    { id: '632',   descripcion: 'ALTA NUEVA DOMESTICO CABECERA MEDIA' },
    { id: '644',   descripcion: 'ALTA P. BAJA DOMESTICO CABECERA MEDIA' },
    { id: '680',   descripcion: 'ALTA NUEVA GANADERO' },
    { id: '732',   descripcion: 'ALTA P. BAJA GANADERO' },
    { id: '744',   descripcion: 'BAJA SUMINISTRO GANADERO' },
    { id: '792',   descripcion: 'ALTA NUEVA HIDRANTE' },
    { id: '804',   descripcion: 'ALTA P. BAJA HIDRANTE' },
    { id: '867',   descripcion: 'BAJA SUMINISTRO DOMESTICO CABECERA MEDIA' },
    { id: '995',   descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL CONDOMINAL' },
    { id: '996',   descripcion: 'ALTA NUEVA DOMESTICO CABECERA MEDIA CONDOMINAL' },
    { id: '997',   descripcion: 'ALTA NUEVA COMERCIAL CONDOMINAL' },
    { id: '998',   descripcion: 'ALTA P. BAJA DOMESTICO ZONA RURAL CONDOMINAL' },
    { id: '999',   descripcion: 'ALTA P. BAJA DOMESTICO CABECERA MEDIA CONDOMINAL' },
    { id: '1000',  descripcion: 'ALTA P. BAJA COMERCIAL CONDOMINAL' },
    { id: '1023',  descripcion: 'CONTRATO ESPECIAL' },
    { id: '1059',  descripcion: 'ALTA NUEVA DOMESTICO ECONOMICO' },
    { id: '1060',  descripcion: 'ALTA P. BAJA DOMESTICO ECONOMICO' },
    { id: '1061',  descripcion: 'BAJA SUMINISTRO DOMESTICO ECONOMICO' },
    { id: '1329',  descripcion: 'ALTA NUEVA DOMESTICO MEDIO' },
    { id: '1330',  descripcion: 'BAJA SUMINISTRO DOMESTICO MEDIO' },
    { id: '1331',  descripcion: 'ALTA P. BAJA DOMESTICO MEDIO' },
    { id: '80099', descripcion: 'ALTA NUEVA DOMESTICO ALTO' },
    { id: '80132', descripcion: 'BAJA SUMINISTRO DOMESTICO ALTO' },
    { id: '80165', descripcion: 'ALTA P. BAJA DOMESTICO ALTO' },
  ],

  '6': [
    { id: '124',   descripcion: 'ALTA NUEVA PUBLICO OFICIAL' },
    { id: '135',   descripcion: 'ALTA NUEVA PUBLICO CONCESIONADO' },
    { id: '146',   descripcion: 'ALTA NUEVA INST. DE BENEFICIENCIA' },
    { id: '168',   descripcion: 'BAJA SUMINISTRO PUBLICO OFICIAL' },
    { id: '179',   descripcion: 'BAJA SUMINISTRO PUBLICO CONCESIONADO' },
    { id: '190',   descripcion: 'BAJA SUMINISTRO INDUSTRIAL' },
    { id: '201',   descripcion: 'BAJA SUMINISTRO INST. DE BENEFICIENCIA' },
    { id: '212',   descripcion: 'BAJA SUMINISTRO COMERCIAL' },
    { id: '333',   descripcion: 'ALTA NUEVA DOMESTICO CABECERA ECONÓMICA' },
    { id: '366',   descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL' },
    { id: '377',   descripcion: 'ALTA NUEVA COMERCIAL' },
    { id: '388',   descripcion: 'ALTA NUEVA INDUSTRIAL' },
    { id: '399',   descripcion: 'BAJA SUMINISTRO DOMESTICO ZONA RURAL' },
    { id: '436',   descripcion: 'ALTA P. BAJA PUBLICO OFICIAL' },
    { id: '448',   descripcion: 'ALTA P. BAJA PUBLICO CONCESIONADO' },
    { id: '460',   descripcion: 'ALTA P. BAJA INST. DE BENEFICIENCIA' },
    { id: '472',   descripcion: 'ALTA P. BAJA INDUSTRIAL' },
    { id: '508',   descripcion: 'ALTA P. BAJA DOMESTICO CABECERA ECONÓMICA' },
    { id: '532',   descripcion: 'ALTA P. BAJA DOMESTICO ZONA RURAL' },
    { id: '556',   descripcion: 'ALTA P. BAJA COMERCIAL' },
    { id: '606',   descripcion: 'GESTION INTERNA' },
    { id: '674',   descripcion: 'ALTA NUEVA GANADERO' },
    { id: '726',   descripcion: 'ALTA P. BAJA GANADERO' },
    { id: '738',   descripcion: 'BAJA SUMINISTRO GANADERO' },
    { id: '786',   descripcion: 'ALTA NUEVA HIDRANTE' },
    { id: '798',   descripcion: 'ALTA P. BAJA HIDRANTE' },
    { id: '852',   descripcion: 'BAJA SUMINISTRO DOMESTICO CABECERA MEDIA' },
    { id: '853',   descripcion: 'BAJA SUMINISTRO DOMESTICO CABECERA ECONÓMICA' },
    { id: '1008',  descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL CONDOMINAL' },
    { id: '1009',  descripcion: 'ALTA NUEVA DOMESTICO CABECERA ECONÓMICA CONDOMINAL' },
    { id: '1010',  descripcion: 'ALTA NUEVA COMERCIAL CONDOMINAL' },
    { id: '1011',  descripcion: 'ALTA P. BAJA DOMESTICO ZONA RURAL CONDOMINAL' },
    { id: '1012',  descripcion: 'ALTA P. BAJA DOMESTICO CABECERA ECONOMICA CONDOMINAL' },
    { id: '1013',  descripcion: 'ALTA P. BAJA COMERCIAL CONDOMINAL' },
    { id: '1035',  descripcion: 'ALTA NUEVA DOMESTICO APOYO SOCIAL' },
    { id: '1036',  descripcion: 'ALTA P. BAJA DOMESTICO APOYO SOCIAL' },
    { id: '1037',  descripcion: 'BAJA SUMINISTRO DOMESTICO APOYO SOCIAL' },
    { id: '1362',  descripcion: 'CONTRATOS ESPECIALES' },
    { id: '80039', descripcion: 'ALTA NUEVA DOMESTICO ECONÓMICO' },
    { id: '80040', descripcion: 'ALTA P. BAJA DOMESTICO ECONÓMICO' },
    { id: '80041', descripcion: 'BAJA SUMINISTRO DOMESTICO ECONÓMICO' },
    { id: '80462', descripcion: 'ALTA NUEVA DOMESTICO MEDIO' },
    { id: '80463', descripcion: 'ALTA NUEVA DOMESTICO ALTO' },
    { id: '80464', descripcion: 'BAJA SUMINISTRO DOMESTICO MEDIO' },
    { id: '80465', descripcion: 'BAJA SUMINISTRO DOMESTICO ALTO' },
    { id: '80466', descripcion: 'ALTA P. BAJA DOMESTICO MEDIO' },
    { id: '80467', descripcion: 'ALTA P. BAJA DOMESTICO ALTO' },
  ],

  '7': [
    { id: '125',   descripcion: 'ALTA NUEVA PUBLICO OFICIAL' },
    { id: '136',   descripcion: 'ALTA NUEVA PUBLICO CONCESIONADO' },
    { id: '147',   descripcion: 'ALTA NUEVA INST. DE BENEFICIENCIA' },
    { id: '169',   descripcion: 'BAJA SUMINISTRO PUBLICO OFICIAL' },
    { id: '180',   descripcion: 'BAJA SUMINISTRO PUBLICO CONCESIONADO' },
    { id: '191',   descripcion: 'BAJA SUMINISTRO INDUSTRIAL' },
    { id: '202',   descripcion: 'BAJA SUMINISTRO INST. DE BENEFICIENCIA' },
    { id: '213',   descripcion: 'BAJA SUMINISTRO COMERCIAL' },
    { id: '334',   descripcion: 'ALTA NUEVA DOMESTICO CABECERA ECONÓMICA' },
    { id: '367',   descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL' },
    { id: '378',   descripcion: 'ALTA NUEVA COMERCIAL' },
    { id: '389',   descripcion: 'ALTA NUEVA INDUSTRIAL' },
    { id: '400',   descripcion: 'BAJA SUMINISTRO DOMESTICO ZONA RURAL' },
    { id: '437',   descripcion: 'ALTA P. BAJA PUBLICO OFICIAL' },
    { id: '449',   descripcion: 'ALTA P. BAJA PUBLICO CONCESIONADO' },
    { id: '461',   descripcion: 'ALTA P. BAJA INST. DE BENEFICIENCIA' },
    { id: '473',   descripcion: 'ALTA P. BAJA INDUSTRIAL' },
    { id: '509',   descripcion: 'ALTA P. BAJA DOMESTICO CABECERA ECONÓMICA' },
    { id: '533',   descripcion: 'ALTA P. BAJA DOMESTICO ZONA RURAL' },
    { id: '557',   descripcion: 'ALTA P. BAJA COMERCIAL' },
    { id: '601',   descripcion: 'GESTION INTERNA' },
    { id: '669',   descripcion: 'ALTA NUEVA GANADERO' },
    { id: '721',   descripcion: 'ALTA P. BAJA GANADERO' },
    { id: '733',   descripcion: 'BAJA SUMINISTRO GANADERO' },
    { id: '781',   descripcion: 'ALTA NUEVA HIDRANTE' },
    { id: '793',   descripcion: 'ALTA P. BAJA HIDRANTE' },
    { id: '842',   descripcion: 'BAJA SUMINISTRO DOMESTICO CABECERA ECONÓMICA' },
    { id: '959',   descripcion: 'ALTA NUEVA COMERCIAL CONDOMINAL' },
    { id: '960',   descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL CONDOMINAL' },
    { id: '961',   descripcion: 'ALTA NUEVA DOMESTICO CABECERA ECONÓMICA CONDOMINAL' },
    { id: '962',   descripcion: 'ALTA P. BAJA COMERCIAL CONDOMINAL' },
    { id: '963',   descripcion: 'ALTA P. BAJA DOMESTICO CABECERA ECONÓMICA CONDOMINAL' },
    { id: '964',   descripcion: 'ALTA P. BAJA DOMESTICO ZONA RURAL CONDOMINAL' },
    { id: '1024',  descripcion: 'CONTRATOS ESPECIALES' },
    { id: '1038',  descripcion: 'ALTA NUEVA DOMESTICO APOYO SOCIAL' },
    { id: '1039',  descripcion: 'ALTA P. BAJA DOMESTICO APOYO SOCIAL' },
    { id: '1040',  descripcion: 'BAJA SUMINISTRO DOMESTICO APOYO SOCIAL' },
    { id: '80000', descripcion: 'ALTA NUEVA DOMESTICO ECONÓMICO' },
    { id: '80001', descripcion: 'ALTA P. BAJA DOMESTICO ECONOMICO' },
    { id: '80002', descripcion: 'BAJA SUMINISTRO DOMESTICO ECONÓMICO' },
    { id: '80759', descripcion: 'ALTA NUEVA DOMESTICO MEDIO' },
    { id: '80792', descripcion: 'ALTA P. BAJA DOMESTICO MEDIO' },
    { id: '80793', descripcion: 'BAJA SUMINISTRO DOMESTICO MEDIO' },
    { id: '80825', descripcion: 'ALTA NUEVA DOMESTICO ALTO' },
    { id: '80826', descripcion: 'ALTA P. BAJA DOMESTICO ALTO' },
    { id: '80827', descripcion: 'BAJA SUMINISTRO DOMESTICO ALTO' },
  ],

  '8': [
    { id: '126',   descripcion: 'ALTA NUEVA PUBLICO OFICIAL' },
    { id: '137',   descripcion: 'ALTA NUEVA PUBLICO CONCESIONADO' },
    { id: '148',   descripcion: 'ALTA NUEVA INST. DE BENEFICIENCIA' },
    { id: '170',   descripcion: 'BAJA SUMINISTRO PUBLICO OFICIAL' },
    { id: '181',   descripcion: 'BAJA SUMINISTRO PUBLICO CONCESIONADO' },
    { id: '192',   descripcion: 'BAJA SUMINISTRO INDUSTRIAL' },
    { id: '203',   descripcion: 'BAJA SUMINISTRO INST. DE BENEFICIENCIA' },
    { id: '214',   descripcion: 'BAJA SUMINISTRO COMERCIAL' },
    { id: '335',   descripcion: 'ALTA NUEVA DOMESTICO CABECERA ECONÓMICA' },
    { id: '368',   descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL' },
    { id: '379',   descripcion: 'ALTA NUEVA COMERCIAL' },
    { id: '390',   descripcion: 'ALTA NUEVA INDUSTRIAL' },
    { id: '401',   descripcion: 'BAJA SUMINISTRO DOMESTICO ZONA RURAL' },
    { id: '438',   descripcion: 'ALTA P. BAJA PUBLICO OFICIAL' },
    { id: '450',   descripcion: 'ALTA P. BAJA PUBLICO CONCESIONADO' },
    { id: '462',   descripcion: 'ALTA P. BAJA INST. DE BENEFICIENCIA' },
    { id: '474',   descripcion: 'ALTA P. BAJA INDUSTRIAL' },
    { id: '510',   descripcion: 'ALTA P. BAJA DOMESTICO CABECERA ECONÓMICA' },
    { id: '534',   descripcion: 'ALTA P. BAJA DOMESTICO ZONA RURAL' },
    { id: '558',   descripcion: 'ALTA P. BAJA COMERCIAL' },
    { id: '607',   descripcion: 'GESTION INTERNA' },
    { id: '675',   descripcion: 'ALTA NUEVA GANADERO' },
    { id: '727',   descripcion: 'ALTA P. BAJA GANADERO' },
    { id: '739',   descripcion: 'BAJA SUMINISTRO GANADERO' },
    { id: '787',   descripcion: 'ALTA NUEVA HIDRANTE' },
    { id: '799',   descripcion: 'ALTA P. BAJA HIDRANTE' },
    { id: '855',   descripcion: 'BAJA SUMINISTRO DOMESTICO CABECERA ECONÓMICA' },
    { id: '1014',  descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL CONDOMINAL' },
    { id: '1015',  descripcion: 'ALTA NUEVA DOMESTICO CABECERA ECONOMICA CONDOMINAL' },
    { id: '1016',  descripcion: 'ALTA NUEVA COMERCIAL CONDOMINAL' },
    { id: '1017',  descripcion: 'ALTA P. BAJA DOMESTICO ZONA RURAL CONDOMINAL' },
    { id: '1018',  descripcion: 'ALTA P. BAJA DOMESTICO CABECERA ECONOMICA CONDOMINAL' },
    { id: '1019',  descripcion: 'ALTA P. BAJA COMERCIAL CONDOMINAL' },
    { id: '1041',  descripcion: 'ALTA NUEVA DOMESTICO APOYO SOCIAL' },
    { id: '1042',  descripcion: 'ALTA P. BAJA DOMESTICO APOYO SOCIAL' },
    { id: '1043',  descripcion: 'BAJA SUMINISTRO DOMESTICO APOYO SOCIAL' },
    { id: '80042', descripcion: 'ALTA NUEVA DOMESTICO ECONÓMICO' },
    { id: '80043', descripcion: 'ALTA P. BAJA DOMESTICO ECONÓMICO' },
    { id: '80044', descripcion: 'BAJA SUMINISTRO DOMESTICO ECONÓMICO' },
    { id: '80297', descripcion: 'ALTA NUEVA DOMESTICO MEDIO' },
    { id: '80330', descripcion: 'ALTA NUEVA DOMESTICO ALTO' },
    { id: '80363', descripcion: 'BAJA SUMINISTRO DOMESTICO MEDIO' },
    { id: '80364', descripcion: 'BAJA SUMINISTRO DOMESTICO ALTO' },
    { id: '80365', descripcion: 'ALTA P. BAJA DOMESTICO MEDIO' },
    { id: '80366', descripcion: 'ALTA P. BAJA DOMESTICO ALTO' },
  ],

  '9': [
    { id: '127',   descripcion: 'ALTA NUEVA PUBLICO OFICIAL' },
    { id: '138',   descripcion: 'ALTA NUEVA PUBLICO CONCESIONADO' },
    { id: '149',   descripcion: 'ALTA NUEVA INST. DE BENEFICIENCIA' },
    { id: '171',   descripcion: 'BAJA SUMINISTRO PUBLICO OFICIAL' },
    { id: '182',   descripcion: 'BAJA SUMINISTRO PUBLICO CONCESIONADO' },
    { id: '193',   descripcion: 'BAJA SUMINISTRO INDUSTRIAL' },
    { id: '204',   descripcion: 'BAJA SUMINISTRO INST. DE BENEFICIENCIA' },
    { id: '215',   descripcion: 'BAJA SUMINISTRO COMERCIAL' },
    { id: '336',   descripcion: 'ALTA NUEVA DOMESTICO CABECERA ECONÓMICA' },
    { id: '369',   descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL' },
    { id: '380',   descripcion: 'ALTA NUEVA COMERCIAL' },
    { id: '391',   descripcion: 'ALTA NUEVA INDUSTRIAL' },
    { id: '402',   descripcion: 'BAJA SUMINISTRO DOMESTICO ZONA RURAL' },
    { id: '439',   descripcion: 'ALTA P. BAJA PUBLICO OFICIAL' },
    { id: '451',   descripcion: 'ALTA P. BAJA PUBLICO CONCESIONADO' },
    { id: '463',   descripcion: 'ALTA P. BAJA INST. DE BENEFICIENCIA' },
    { id: '475',   descripcion: 'ALTA P. BAJA INDUSTRIAL' },
    { id: '511',   descripcion: 'ALTA P. BAJA DOMESTICO CABECERA ECONÓMICA' },
    { id: '535',   descripcion: 'ALTA P. BAJA DOMESTICO ZONA RURAL' },
    { id: '559',   descripcion: 'ALTA P. BAJA COMERCIAL' },
    { id: '602',   descripcion: 'GESTION INTERNA' },
    { id: '670',   descripcion: 'ALTA NUEVA GANADERO' },
    { id: '722',   descripcion: 'ALTA P. BAJA GANADERO' },
    { id: '734',   descripcion: 'BAJA SUMINISTRO GANADERO' },
    { id: '783',   descripcion: 'ALTA NUEVA HIDRANTE' },
    { id: '794',   descripcion: 'ALTA P. BAJA HIDRANTE' },
    { id: '843',   descripcion: 'BAJA SUMINISTRO DOMESTICO CABECERA MEDIA' },
    { id: '844',   descripcion: 'BAJA SUMINISTRO DOMESTICO CABECERA ECONÓMICA' },
    { id: '965',   descripcion: 'ALTA NUEVA DOMÉSTICO CABECERA ECONÓMICA CONDOMINAL' },
    { id: '966',   descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL CONDOMINAL' },
    { id: '973',   descripcion: 'ALTA NUEVA COMERCIAL CONDOMINAL' },
    { id: '974',   descripcion: 'ALTA P. BAJA DOMESTICO ZONA RURAL CONDOMINAL' },
    { id: '975',   descripcion: 'ALTA P. BAJA DOMESTICO CABECERA ECONÓMICA CONDOMINAL' },
    { id: '976',   descripcion: 'ALTA P. BAJA COMERCIAL CONDOMINAL' },
    { id: '1032',  descripcion: 'ALTA NUEVA DOMESTICO APOYO SOCIAL' },
    { id: '1033',  descripcion: 'ALTA P. BAJA DOMESTICO APOYO SOCIAL' },
    { id: '1034',  descripcion: 'BAJA SUMINISTRO DOMESTICO APOYO SOCIAL' },
    { id: '1197',  descripcion: 'CONTRATOS ESPECIALES' },
    { id: '80033', descripcion: 'ALTA NUEVA DOMESTICO ECONÓMICO' },
    { id: '80034', descripcion: 'ALTA P. BAJA DOMESTICO ECONÓMICO' },
    { id: '80035', descripcion: 'BAJA SUMINISTRO DOMESTICO ECONÓMICO' },
    { id: '80528', descripcion: 'ALTA NUEVA DOMESTICO ALTO' },
    { id: '80561', descripcion: 'ALTA NUEVA DOMESTICO MEDIO' },
    { id: '80594', descripcion: 'BAJA SUMINISTRO DOMESTICO MEDIO' },
    { id: '80595', descripcion: 'BAJA SUMINISTRO DOMESTICO ALTO' },
    { id: '80596', descripcion: 'ALTA P. BAJA DOMESTICO MEDIO' },
    { id: '80597', descripcion: 'ALTA P. BAJA DOMESTICO ALTO' },
  ],

  '10': [
    { id: '10001', descripcion: 'ALTA NUEVA PUBLICO OFICIAL' },
    { id: '10002', descripcion: 'ALTA NUEVA PUBLICO CONCESIONADO' },
    { id: '10003', descripcion: 'ALTA NUEVA INST. DE BENEFICIENCIA' },
    { id: '10004', descripcion: 'ALTA P. BAJA GANADERO' },
    { id: '10005', descripcion: 'BAJA SUMINISTRO PUBLICO OFICIAL' },
    { id: '10006', descripcion: 'BAJA SUMINISTRO PUBLICO CONCESIONADO' },
    { id: '10007', descripcion: 'BAJA SUMINISTRO INDUSTRIAL' },
    { id: '10008', descripcion: 'BAJA SUMINISTRO INST. DE BENEFICIENCIA' },
    { id: '10009', descripcion: 'BAJA SUMINISTRO COMERCIAL' },
    { id: '10010', descripcion: 'ALTA P. BAJA PUBLICO OFICIAL' },
    { id: '10011', descripcion: 'ALTA P. BAJA PUBLICO CONCESIONADO' },
    { id: '10012', descripcion: 'ALTA P. BAJA INST. DE BENEFICIENCIA' },
    { id: '10013', descripcion: 'ALTA P. BAJA INDUSTRIAL' },
    { id: '10014', descripcion: 'BAJA SUMINISTRO GANADERO' },
    { id: '10015', descripcion: 'ALTA P. BAJA DOMESTICO CABECERA ECONÓMICA' },
    { id: '10016', descripcion: 'ALTA P. BAJA DOMESTICO ZONA RURAL' },
    { id: '10017', descripcion: 'ALTA P. BAJA DOMESTICO CABECERA ECONOMICA CONDOMINAL' },
    { id: '10018', descripcion: 'ALTA P. BAJA DOMESTICO ZONA RURAL CONDOMINAL' },
    { id: '10019', descripcion: 'ALTA P. BAJA COMERCIAL' },
    { id: '10020', descripcion: 'BAJA SUMINISTRO DOMESTICO CABECERA MEDIA' },
    { id: '10021', descripcion: 'ALTA NUEVA DOMESTICO CABECERA ECONÓMICA' },
    { id: '10022', descripcion: 'BAJA SUMINISTRO CABECERA ECONÓMICA' },
    { id: '10023', descripcion: 'BAJA SUMINISTRO DOMESTICO CABECERA ECONÓMICA' },
    { id: '10024', descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL' },
    { id: '10025', descripcion: 'ALTA NUEVA COMERCIAL' },
    { id: '10026', descripcion: 'ALTA NUEVA INDUSTRIAL' },
    { id: '10027', descripcion: 'BAJA SUMINISTRO DOMESTICO ZONA RURAL' },
    { id: '10028', descripcion: 'ALTA NUEVA HIDRANTE' },
    { id: '10029', descripcion: 'GESTION INTERNA' },
    { id: '10030', descripcion: 'ALTA P. BAJA HIDRANTE' },
    { id: '10031', descripcion: 'ALTA NUEVA GANADERO' },
    { id: '10032', descripcion: 'ALTA P. BAJA COMERCIAL CONDOMINAL' },
    { id: '10033', descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL CONDOMINAL' },
    { id: '10034', descripcion: 'ALTA NUEVA DOMESTICO APOYO SOCIAL' },
    { id: '10035', descripcion: 'ALTA P. BAJA DOMESTICO APOYO SOCIAL' },
    { id: '10036', descripcion: 'BAJA SUMINISTRO DOMESTICO APOYO SOCIAL' },
    { id: '10037', descripcion: 'ALTA NUEVA DOMESTICO CABECERA ECONOMICA CONDOMINAL' },
    { id: '10038', descripcion: 'ALTA NUEVA COMERCIAL CONDOMINAL' },
    { id: '10039', descripcion: 'CONTRATOS ESPECIALES' },
    { id: '10040', descripcion: 'ALTA NUEVA DOMESTICO ECONÓMICO' },
    { id: '10041', descripcion: 'ALTA P. BAJA DOMESTICO ECONÓMICO' },
    { id: '10042', descripcion: 'BAJA SUMINISTRO DOMESTICO ECONÓMICO' },
    { id: '10043', descripcion: 'ALTA NUEVA DOMESTICO MEDIO' },
    { id: '10044', descripcion: 'ALTA NUEVA DOMESTICO ALTO' },
    { id: '10045', descripcion: 'BAJA SUMINISTRO DOMESTICO MEDIO' },
    { id: '10046', descripcion: 'BAJA SUMINISTRO DOMESTICO ALTO' },
    { id: '10047', descripcion: 'ALTA P. BAJA DOMESTICO MEDIO' },
    { id: '10048', descripcion: 'ALTA P. BAJA DOMESTICO ALTO' },
  ],

  '11': [
    { id: '129',   descripcion: 'ALTA NUEVA PUBLICO OFICIAL' },
    { id: '140',   descripcion: 'ALTA NUEVA PUBLICO CONCESIONADO' },
    { id: '151',   descripcion: 'ALTA NUEVA INST. DE BENEFICIENCIA' },
    { id: '173',   descripcion: 'BAJA SUMINISTRO PUBLICO OFICIAL' },
    { id: '184',   descripcion: 'BAJA SUMINISTRO PUBLICO CONCESIONADO' },
    { id: '195',   descripcion: 'BAJA SUMINISTRO INDUSTRIAL' },
    { id: '206',   descripcion: 'BAJA SUMINISTRO INST. DE BENEFICIENCIA' },
    { id: '217',   descripcion: 'BAJA SUMINISTRO COMERCIAL' },
    { id: '338',   descripcion: 'ALTA NUEVA DOMESTICO CABECERA ECONÓMICA' },
    { id: '371',   descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL' },
    { id: '382',   descripcion: 'ALTA NUEVA COMERCIAL' },
    { id: '393',   descripcion: 'ALTA NUEVA INDUSTRIAL' },
    { id: '404',   descripcion: 'BAJA SUMINISTRO DOMESTICO ZONA RURAL' },
    { id: '441',   descripcion: 'ALTA P. BAJA PUBLICO OFICIAL' },
    { id: '453',   descripcion: 'ALTA P. BAJA PUBLICO CONCESIONADO' },
    { id: '465',   descripcion: 'ALTA P. BAJA INST. DE BENEFICIENCIA' },
    { id: '477',   descripcion: 'ALTA P. BAJA INDUSTRIAL' },
    { id: '513',   descripcion: 'ALTA P. BAJA DOMESTICO CABECERA ECONÓMICA' },
    { id: '537',   descripcion: 'ALTA P. BAJA DOMESTICO ZONA RURAL' },
    { id: '561',   descripcion: 'ALTA P. BAJA COMERCIAL' },
    { id: '608',   descripcion: 'GESTION INTERNA' },
    { id: '676',   descripcion: 'ALTA NUEVA GANADERO' },
    { id: '728',   descripcion: 'ALTA P. BAJA GANADERO' },
    { id: '740',   descripcion: 'BAJA SUMINISTRO GANADERO' },
    { id: '788',   descripcion: 'ALTA NUEVA HIDRANTE' },
    { id: '800',   descripcion: 'ALTA P. BAJA HIDRANTE' },
    { id: '856',   descripcion: 'BAJA SUMINISTRO DOMESTICO CABECERA MEDIA' },
    { id: '857',   descripcion: 'BAJA SUMINISTRO DOMESTICO CABECERA ECONÓMICA' },
    { id: '1020',  descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL CONDOMINAL' },
    { id: '1056',  descripcion: 'ALTA NUEVA DOMESTICO APOYO SOCIAL' },
    { id: '1057',  descripcion: 'ALTA P. BAJA DOMESTICO APOYO SOCIAL' },
    { id: '1058',  descripcion: 'BAJA SUMINISTRO DOMESTICO APOYO SOCIAL' },
    { id: '80045', descripcion: 'ALTA NUEVA DOMESTICO ECONÓMICO' },
    { id: '80046', descripcion: 'ALTA P. BAJA DOMESTICO ECONÓMICO' },
    { id: '80047', descripcion: 'BAJA SUMINISTRO DOMESTICO ECONÓMICO' },
    { id: '80066', descripcion: 'CONTRATOS ESPECIALES' },
    { id: '80627', descripcion: 'ALTA NUEVA DOMESTICO MEDIO' },
    { id: '80660', descripcion: 'ALTA P. BAJA DOMESTICO MEDIO' },
    { id: '80661', descripcion: 'BAJA SUMINISTRO DOMESTICO MEDIO' },
    { id: '80693', descripcion: 'ALTA NUEVA DOMESTICO ALTO' },
    { id: '80726', descripcion: 'BAJA SUMINISTRO DOMESTICO ALTO' },
  ],

  '12': [
    { id: '130',   descripcion: 'ALTA NUEVA PUBLICO OFICIAL' },
    { id: '141',   descripcion: 'ALTA NUEVA PUBLICO CONCESIONADO' },
    { id: '152',   descripcion: 'ALTA NUEVA INST. DE BENEFICIENCIA' },
    { id: '174',   descripcion: 'BAJA SUMINISTRO PUBLICO OFICIAL' },
    { id: '185',   descripcion: 'BAJA SUMINISTRO PUBLICO CONCESIONADO' },
    { id: '196',   descripcion: 'BAJA SUMINISTRO INDUSTRIAL' },
    { id: '207',   descripcion: 'BAJA SUMINISTRO INST. DE BENEFICIENCIA' },
    { id: '218',   descripcion: 'BAJA SUMINISTRO COMERCIAL' },
    { id: '372',   descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL' },
    { id: '383',   descripcion: 'ALTA NUEVA COMERCIAL' },
    { id: '394',   descripcion: 'ALTA NUEVA INDUSTRIAL' },
    { id: '405',   descripcion: 'BAJA SUMINISTRO DOMESTICO ZONA RURAL' },
    { id: '442',   descripcion: 'ALTA P. BAJA PUBLICO OFICIAL' },
    { id: '454',   descripcion: 'ALTA P. BAJA PUBLICO CONCESIONADO' },
    { id: '466',   descripcion: 'ALTA P. BAJA INST. DE BENEFICIENCIA' },
    { id: '478',   descripcion: 'ALTA P. BAJA INDUSTRIAL' },
    { id: '538',   descripcion: 'ALTA P. BAJA DOMESTICO ZONA RURAL' },
    { id: '562',   descripcion: 'ALTA P. BAJA COMERCIAL' },
    { id: '605',   descripcion: 'GESTION INTERNA' },
    { id: '625',   descripcion: 'ALTA NUEVA DOMESTICO CABECERA MEDIA' },
    { id: '637',   descripcion: 'ALTA P. BAJA DOMESTICO CABECERA MEDIA' },
    { id: '673',   descripcion: 'ALTA NUEVA GANADERO' },
    { id: '725',   descripcion: 'ALTA P. BAJA GANADERO' },
    { id: '737',   descripcion: 'BAJA SUMINISTRO GANADERO' },
    { id: '785',   descripcion: 'ALTA NUEVA HIDRANTE' },
    { id: '797',   descripcion: 'ALTA P. BAJA HIDRANTE' },
    { id: '850',   descripcion: 'BAJA SUMINISTRO DOMESTICO CABECERA MEDIA' },
    { id: '851',   descripcion: 'BAJA SUMINISTRO DOMESTICO CABECERA ECONÓMICA' },
    { id: '882',   descripcion: 'BAJA SUMINISTRO HIDRANTE' },
    { id: '989',   descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL CONDOMINAL' },
    { id: '990',   descripcion: 'ALTA NUEVA DOMESTICO CABECERA MEDIA CONDOMINAL' },
    { id: '991',   descripcion: 'ALTA NUEVA COMERCIAL CONDOMINAL' },
    { id: '992',   descripcion: 'ALTA P. BAJA DOMESTICO ZONA RURAL CONDOMINAL' },
    { id: '993',   descripcion: 'ALTA P. BAJA DOMESTICO CABECERA MEDIA CONDOMINAL' },
    { id: '994',   descripcion: 'ALTA P. BAJA COMERCIAL CONDOMINAL' },
    { id: '1021',  descripcion: 'CONTRATO ESPECIAL' },
    { id: '1027',  descripcion: 'ALTA NUEVA DOMESTICO MEDIO' },
    { id: '1028',  descripcion: 'BAJA SUMINISTRO DOMESTICO MEDIO' },
    { id: '1062',  descripcion: 'ALTA NUEVA DOMESTICO ECONOMICO' },
    { id: '1063',  descripcion: 'ALTA P. BAJA DOMESTICO ECONOMICO' },
    { id: '1064',  descripcion: 'BAJA SUMINISTRO DOMESTICO ECONOMICO' },
    { id: '80231', descripcion: 'ALTA NUEVA DOMESTICO ALTO' },
    { id: '80264', descripcion: 'BAJA SUMINISTRO DOMESTICO ALTO' },
    { id: '80265', descripcion: 'ALTA P. BAJA DOMESTICO MEDIO' },
    { id: '80266', descripcion: 'ALTA P. BAJA DOMESTICO ALTO' },
  ],

  '13': [
    { id: '131',   descripcion: 'ALTA NUEVA PUBLICO OFICIAL' },
    { id: '142',   descripcion: 'ALTA NUEVA PUBLICO CONCESIONADO' },
    { id: '153',   descripcion: 'ALTA NUEVA INST. DE BENEFICIENCIA' },
    { id: '175',   descripcion: 'BAJA SUMINISTRO PUBLICO OFICIAL' },
    { id: '186',   descripcion: 'BAJA SUMINISTRO PUBLICO CONCESIONADO' },
    { id: '197',   descripcion: 'BAJA SUMINISTRO INDUSTRIAL' },
    { id: '208',   descripcion: 'BAJA SUMINISTRO INST. DE BENEFICIENCIA' },
    { id: '219',   descripcion: 'BAJA SUMINISTRO COMERCIAL' },
    { id: '340',   descripcion: 'ALTA NUEVA DOMESTICO CABECERA ECONÓMICA' },
    { id: '373',   descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL' },
    { id: '384',   descripcion: 'ALTA NUEVA COMERCIAL' },
    { id: '395',   descripcion: 'ALTA NUEVA INDUSTRIAL' },
    { id: '406',   descripcion: 'BAJA SUMINISTRO DOMESTICO ZONA RURAL' },
    { id: '443',   descripcion: 'ALTA P. BAJA PUBLICO OFICIAL' },
    { id: '455',   descripcion: 'ALTA P. BAJA PUBLICO CONCESIONADO' },
    { id: '467',   descripcion: 'ALTA P. BAJA INST. DE BENEFICIENCIA' },
    { id: '479',   descripcion: 'ALTA P. BAJA INDUSTRIAL' },
    { id: '515',   descripcion: 'ALTA P. BAJA DOMESTICO CABECERA ECONÓMICA' },
    { id: '539',   descripcion: 'ALTA P. BAJA DOMESTICO ZONA RURAL' },
    { id: '563',   descripcion: 'ALTA P. BAJA COMERCIAL' },
    { id: '610',   descripcion: 'GESTION INTERNA' },
    { id: '678',   descripcion: 'ALTA NUEVA GANADERO' },
    { id: '730',   descripcion: 'ALTA P. BAJA GANADERO' },
    { id: '742',   descripcion: 'BAJA SUMINISTRO GANADERO' },
    { id: '790',   descripcion: 'ALTA NUEVA HIDRANTE' },
    { id: '802',   descripcion: 'ALTA P. BAJA HIDRANTE' },
    { id: '861',   descripcion: 'BAJA SUMINISTRO DOMESTICO CABECERA ECONÓMICA' },
    { id: '1001',  descripcion: 'ALTA NUEVA DOMESTICO ZONA RURAL CONDOMINAL' },
    { id: '1002',  descripcion: 'ALTA NUEVA DOMESTICO CABECERA ECONOMICA CONDOMINAL' },
    { id: '1003',  descripcion: 'ALTA NUEVA COMERCIAL CONDOMINAL' },
    { id: '1004',  descripcion: 'ALTA P. BAJA DOMESTICO ZONA RURAL CONDOMINAL' },
    { id: '1005',  descripcion: 'ALTA P. BAJA DOMESTICO CABECERA ECONOMICA CONDOMINAL' },
    { id: '1006',  descripcion: 'ALTA P. BAJA COMERCIAL CONDOMINAL' },
    { id: '1050',  descripcion: 'ALTA NUEVA DOMESTICO APOYO SOCIAL' },
    { id: '1051',  descripcion: 'ALTA P. BAJA DOMESTICO APOYO SOCIAL' },
    { id: '1052',  descripcion: 'BAJA SUMINISTRO DOMESTICO APOYO SOCIAL' },
    { id: '1230',  descripcion: 'CONTRATOS ESPECIALES' },
    { id: '80051', descripcion: 'ALTA NUEVA DOMESTICO ECONÓMICO' },
    { id: '80052', descripcion: 'ALTA P. BAJA DOMESTICO ECONÓMICO' },
    { id: '80053', descripcion: 'BAJA SUMINISTRO DOMESTICO ECONÓMICO' },
  ],
};
