/** Catálogos UI compartidos entre pasos de configuración y resumen del wizard. */

export const CLASES_CONTRATACION: { cod: string; descripcion: string }[] = [
  { cod: 'AN', descripcion: 'Alta Nueva' },
  { cod: 'CN', descripcion: 'Cambio Nombre' },
  { cod: 'PB', descripcion: 'Alta Procede de Baja' },
  { cod: 'BJ', descripcion: 'Baja' },
];

export const TIPOS_PUNTO_SERVICIO: { id: string; descripcion: string }[] = [
  { id: '1', descripcion: 'DOMESTICO APOYO SOCIAL' },
  { id: '2', descripcion: 'COMERCIAL' },
  { id: '3', descripcion: 'OBRAS' },
  { id: '4', descripcion: 'COMUNIDAD PROPIETARIOS' },
  { id: '5', descripcion: 'CONTRAINCENDIOS' },
  { id: '6', descripcion: 'RIEGO/BALDEO' },
  { id: '7', descripcion: 'VIVIENDA P.O.' },
  { id: '8', descripcion: 'SUMINISTRO BUQUES' },
  { id: '9', descripcion: 'DESCALCIFICADOR' },
  { id: '10', descripcion: 'FUENTES' },
  { id: '11', descripcion: 'INDUSTRIAL' },
  { id: '12', descripcion: 'AGUA EN ALTA' },
  { id: '13', descripcion: 'GENERAL' },
  { id: '14', descripcion: 'PISCINAS' },
  { id: '15', descripcion: 'FREATICA' },
  { id: '16', descripcion: 'AGRICOLA' },
  { id: '17', descripcion: 'GANADERO' },
  { id: '18', descripcion: 'SIN SUMINISTRO (USO DOMESTICO)' },
  { id: '19', descripcion: 'SIN SUMINISTRO (INDUSTRIAL)' },
  { id: '20', descripcion: 'CUBAS' },
  { id: '21', descripcion: 'COMPLEJO TURÍSTICO' },
  { id: '60', descripcion: 'ZONAS COMUNES' },
  { id: '80', descripcion: 'HUERTO' },
  { id: '100', descripcion: 'PIME' },
  { id: '101', descripcion: 'EVENTUAL' },
  { id: '102', descripcion: 'PUBLICO OFICIAL' },
  { id: '103', descripcion: 'PUBLICO CONCESIONADO' },
  { id: '104', descripcion: 'HIDRANTE' },
  { id: '105', descripcion: 'INST. DE BENEFICIENCIA' },
  { id: '122', descripcion: 'DOMÉSTICO ECONÓMICO' },
  { id: '123', descripcion: 'DOMÉSTICO MEDIO' },
  { id: '124', descripcion: 'DOMÉSTICO ALTO' },
  { id: '125', descripcion: 'DOMÉSTICO ZONA RURAL' },
  { id: '126', descripcion: 'DOMÉSTICO CABECERA ECONÓMICA' },
  { id: '127', descripcion: 'DOMÉSTICO CABECERA MEDIA' },
];
