import type { SolicitudInspeccionDto } from '@/api/solicitudes';
import type { OrdenInspeccionData } from '@/types/solicitudes';

/** Maps API DTO → form/view shape (same as Solicitudes.tsx). */
export function solicitudInspeccionDtoToOrden(insp: SolicitudInspeccionDto): OrdenInspeccionData {
  return {
    estado: insp.estado as OrdenInspeccionData['estado'],
    fechaInspeccion: insp.fechaInspeccion ?? undefined,
    numeroOficial: insp.numeroOficial ?? undefined,
    tipoUso: insp.tipoUso ?? undefined,
    giro: insp.giro ?? undefined,
    areaTerreno: insp.areaTerreno ?? undefined,
    condicionToma: insp.condicionToma ?? undefined,
    condicionesPredio: insp.condicionesPredio ?? undefined,
    infraHidraulicaExterna: (insp.infraHidraulicaExterna as 'si' | 'no' | '') ?? '',
    infraSanitaria: (insp.infraSanitaria as 'si' | 'no' | '') ?? '',
    materialCalle: insp.materialCalle ?? undefined,
    materialBanqueta: insp.materialBanqueta ?? undefined,
    metrosRupturaAguaBanqueta: insp.metrosRupturaAguaBanqueta ?? undefined,
    metrosRupturaAguaCalle: insp.metrosRupturaAguaCalle ?? undefined,
    metrosRupturaDrenajeBanqueta: insp.metrosRupturaDrenajeBanqueta ?? undefined,
    metrosRupturaDrenajeCalle: insp.metrosRupturaDrenajeCalle ?? undefined,
    observaciones: insp.observaciones ?? undefined,
    evidencias: (insp.evidencias as string[]) ?? undefined,
    resultadoEjecucion: insp.resultadoEjecucion ?? undefined,
    resultadoInspeccion: insp.resultadoInspeccion ?? undefined,
    inspectorNumEmpleado: insp.inspectorNumEmpleado ?? undefined,
    inspectorNombre: insp.inspectorNombre ?? undefined,
    firmaInspector: insp.firmaInspector ?? undefined,
    inspectoresAdicionales: (insp.inspectoresAdicionales as OrdenInspeccionData['inspectoresAdicionales']) ?? undefined,
    inicio: insp.inicio ?? undefined,
    fin: insp.fin ?? undefined,
    tipoOrdenCorrecto: (insp.tipoOrdenCorrecto as 'si' | 'no' | '') ?? '',
    inspector: insp.inspector ?? undefined,
    diametroToma: insp.diametroToma ?? undefined,
    medidorExistente: (insp.medidorExistente as 'si' | 'no' | '') ?? '',
    numMedidorExistente: insp.numMedidorExistente ?? undefined,
    metrosRupturaCalle: insp.metrosRupturaCalle ?? undefined,
    metrosRupturaBanqueta: insp.metrosRupturaBanqueta ?? undefined,
    existeRed: (insp.existeRed as 'si' | 'no' | '') ?? '',
    distanciaRed: insp.distanciaRed ?? undefined,
    presionRed: insp.presionRed ?? undefined,
    tipoMaterialRed: insp.tipoMaterialRed ?? undefined,
    profundidadRed: insp.profundidadRed ?? undefined,
    tomaExistente: insp.tomaExistente ?? undefined,
    diametroTomaExistente: insp.diametroTomaExistente ?? undefined,
    estadoTomaExistente: insp.estadoTomaExistente ?? undefined,
  };
}
